name: Update Image

on:
  schedule:
    - cron:  '59 * * * *'

jobs:
  Run-Update-Script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-tags: true
          fetch-depth: 0
      - run: git config --global user.email "${{ secrets.GIT_EMAIL }}"
      - run: git config --global user.name "${{ github.actor }}"
      - run: ./update.sh --noconfirm
